name: Build Pikabox Live ISO
on: [push, workflow_dispatch]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Repositories and Install KIWI
        run: |
          sudo apt-get update
          sudo apt-get install -y kiwi-tools python3-kiwi qemu-utils

      - name: Build Live Image
        run: |
          sudo mkdir -p ./build_output
          sudo kiwi-ng --profile=default image build \
            --description ./ \
            --target-dir ./build_output

      - name: Upload Finished ISO
        uses: actions/upload-artifact@v4
        with:
          name: pikabox-twilight-iso
          path: ./build_output/*.iso
